version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: software.amazon.awssdk:bom
    versions:
    - 2.15.69
    - 2.15.73
    - 2.15.77
    - 2.15.81
    - 2.16.13
    - 2.16.18
    - 2.16.23
    - 2.16.29
    - 2.16.3
    - 2.16.34
    - 2.16.39
    - 2.16.43
    - 2.16.8
