version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-buster

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn -s .circleci/settings.xml dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Static analysis
      - run: mvn -s .circleci/settings.xml checkstyle:checkstyle

      # Unit & Integration Tests
      - run: mvn -s .circleci/settings.xml verify

     # - run: mvn sonar:sonar

#workflows:
#  main:
#    jobs:
#      - build:
#          context: SonarCloud